name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build_linux:
    name: Ubuntu Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Odin
      - uses: actions/checkout@v4
        with:
          repository: Odin-lang/odin

      - name: Build Odin
        run: |
          ./build_odin.sh

      - name: Build Spall
        run: |
          ./build.sh release
