name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build_linux:
    name: Ubuntu Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Grab Spall Dependencies
        run: |
          sudo apt install libsdl2-dev libsdl2-ttf-dev
    
      - name: Checkout Spall
        uses: actions/checkout@v4
    
      - name: Checkout Odin
        uses: actions/checkout@v4
        with:
          repository: Odin-lang/odin
          path: odin

      - name: Build Odin
        run: |
          cd odin
          ./build_odin.sh
          echo $PWD >> $GITHUB_PATH
        
      - name: Build Spall
        run: |
          ./build.sh release

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux_artifacts
          path: bin

  build_mac_x86:
    name: OSX x86 Build and Test
    runs-on: macos-latest
    steps:
      - name: Grab Spall Dependencies
        run: |
          brew install sdl2 sdl2_ttf llvm@17
          echo "/usr/local/opt/llvm@17/bin" >> $GITHUB_PATH
    
      - name: Checkout Spall
        uses: actions/checkout@v4
    
      - name: Checkout Odin
        uses: actions/checkout@v4
        with:
          repository: Odin-lang/odin
          path: odin

      - name: Build Odin
        run: |
          cd odin
          ./build_odin.sh
          echo $PWD >> $GITHUB_PATH
        
      - name: Build Spall
        run: |
          ./build.sh release

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: osx_x86_artifacts
          path: bin

  build_mac_arm:
    name: OSX ARM Build and Test
    runs-on: macos-14
    steps:
      - name: Grab Spall Dependencies
        run: |
          brew install sdl2 sdl2_ttf llvm@17
          echo "/opt/homebrew/opt/llvm@17/bin" >> $GITHUB_PATH
    
      - name: Checkout Spall
        uses: actions/checkout@v4
    
      - name: Checkout Odin
        uses: actions/checkout@v4
        with:
          repository: Odin-lang/odin
          path: odin

      - name: Build Odin
        run: |
          cd odin
          ./build_odin.sh
          echo $PWD >> $GITHUB_PATH
        
      - name: Build Spall
        run: |
          ./build.sh release

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: osx_arm_artifacts
          path: bin

  build_windows:
    name: Windows Build and Test
    runs-on: windows-2022
    steps:
      - name: Checkout Spall
        uses: actions/checkout@v4
    
      - name: Checkout Odin
        uses: actions/checkout@v4
        with:
          repository: Odin-lang/odin
          path: odin

      - name: Build Odin
        run: |
          cd odin
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          & ./build.bat
          $CUR_PATH = (Get-Item .).FullName
          Add-Content $env:GITHUB_PATH $CUR_PATH
        
      - name: Build Spall
        run: |
          odin build
